var CHART_TYPE = [
	{"id":"line1","text":"折线图"},
	{"id":"line3","text":"面积图"},
	{"id":"bar1","text":"标准柱状图"},
	{"id":"bar2","text":"堆积柱状图"},
	{"id":"pie1","text":"饼图"},
	{"id":"list","text":"列表"}
	/*,
	{"id":"mix1","text":"折柱混搭"},
	{"id":"mix2","text":"柱状饼混搭"},
	{"id":"mix3","text":"折线面积混搭"}*/
	//,
	//{"id":"dataZoom1","text":"数据区域缩放"},
	//{"id":"dynamicLineBar","text":"动态数据"}
];
var MIX_TYPE_1 = [
	{"id":"line","text":"折线图"},
	{"id":"bar","text":"柱状图"}
];
var MIX_TYPE_2 = [
   	{"id":"bar","text":"柱状图"},
   	{"id":"pie","text":"饼图"}
];
var MIX_TYPE_3 = [
   	{"id":"line","text":"折线图"},
   	{"id":"line","text":"面积图"}
];
var CHART_DATA = {
"line1":{color:['red', 'green','yellow'],title:{text:'未来一周气温变化',subtext:'纯属虚构',x:'left'},tooltip:{trigger:'axis'},legend:{data:['最高气温','最低气温']},toolbox:{show:true,feature:{mark:{show:false},dataView:{show:false,readOnly:false},magicType:{show:false,type:['line','bar']},restore:{show:true},saveAsImage:{show:true}}},calculable:true,xAxis:[{type:'category',boundaryGap:false,data:['周一','周二','周三','周四','周五','周六','周日']}],yAxis:[{type:'value',axisLabel:{formatter:'{value}°C'},name:'测测测算',nameLocation:'start'}],series:[{name:'最高气温',type:'line',data:[11,11,15,13,12,13,10],markPoint:{data:[{type:'max',name:'最大值'},{type:'min',name:'最小值'}]},markLine:{data:[{type:'average',name:'平均值'}]}},{name:'最低气温',type:'line',data:[1,-2,2,5,3,2,0],markPoint:{data:[{name:'周最低',value:-2,xAxis:1,yAxis:-1.5}]},markLine:{data:[{type:'average',name:'平均值'}]}}]},
"line3":{color:['red', 'green','yellow'],title:{text:'某楼盘销售情况',subtext:'纯属虚构',x:'left'},tooltip:{trigger:'axis'},legend:{data:['意向','预购','成交']},toolbox:{show:true,feature:{mark:{show:false},dataView:{show:false,readOnly:false},magicType:{show:false,type:['line','bar','stack','tiled']},restore:{show:true},saveAsImage:{show:true}}},calculable:true,xAxis:[{type:'category',boundaryGap:false,data:['周一','周二','周三','周四','周五','周六','周日']}],yAxis:[{type:'value'}],series:[{name:'成交',type:'line',smooth:true,itemStyle:{normal:{areaStyle:{type:'default'}}},data:[10,12,21,54,260,830,710]},{name:'预购',type:'line',smooth:true,itemStyle:{normal:{areaStyle:{type:'default'}}},data:[30,182,434,791,390,30,10]},{name:'意向',type:'line',smooth:true,itemStyle:{normal:{areaStyle:{type:'default'}}},data:[1320,1132,601,234,120,90,20]}]},
"bar1":{color:['red', 'green','yellow'],title:{text:'某地区蒸发量和降水量',subtext:'纯属虚构',x:'left'},tooltip:{trigger:'axis'},legend:{data:['蒸发量','降水量']},toolbox:{show:true,feature:{mark:{show:false},dataView:{show:false,readOnly:false},magicType:{show:false,type:['line','bar']},restore:{show:true},saveAsImage:{show:true}}},calculable:true,xAxis:[{type:'category',data:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']}],yAxis:[{type:'value'}],series:[{name:'蒸发量',type:'bar',data:[2.0,4.9,7.0,23.2,25.6,76.7,135.6,162.2,32.6,20.0,6.4,3.3],markPoint:{data:[{type:'max',name:'最大值'},{type:'min',name:'最小值'}]},markLine:{data:[{type:'average',name:'平均值'}]}},{name:'降水量',type:'bar',data:[2.6,5.9,9.0,26.4,28.7,70.7,175.6,182.2,48.7,18.8,6.0,2.3],markPoint:{data:[{name:'年最高',value:182.2,xAxis:7,yAxis:183,symbolSize:18},{name:'年最低',value:2.3,xAxis:11,yAxis:3}]},markLine:{data:[{type:'average',name:'平均值'}]}}]},
"pie1":{color:['red', 'green','yellow'],title:{text:'某站点用户访问来源',subtext:'纯属虚构',x:'center'},tooltip:{trigger:'item',formatter:"{a}<br/>{b}:{c}({d}%)"},legend:{orient:'vertical',x:'left',data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']},toolbox:{show:true,feature:{mark:{show:false},dataView:{show:false,readOnly:false},magicType:{show:false,type:['pie','funnel'],option:{funnel:{x:'25%',width:'50%',funnelAlign:'left',max:1548}}},restore:{show:true},saveAsImage:{show:true}}},calculable:true,series:[{name:'访问来源',type:'pie',radius:'55%',center:['50%','60%'],data:[{value:335,name:'直接访问'},{value:310,name:'邮件营销'},{value:234,name:'联盟广告'},{value:135,name:'视频广告'},{value:1548,name:'搜索引擎'}]}]},
"mix1":{color:['red', 'green','yellow'],title:{text:'某站点用户访问来源',subtext:'纯属虚构',x:'left'},tooltip:{trigger:'axis'},toolbox:{show:true,feature:{mark:{show:false},dataView:{show:true,readOnly:false},magicType:{show:true,type:['line','bar']},restore:{show:true},saveAsImage:{show:true}}},calculable:true,legend:{data:['蒸发量','降水量','平均温度']},xAxis:[{type:'category',data:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']}],yAxis:[{type:'value',name:'水量',axisLabel:{formatter:'{value}ml'}},{type:'value',name:'温度',axisLabel:{formatter:'{value}°C'}}],series:[{name:'蒸发量',type:'bar',data:[2.0,4.9,7.0,23.2,25.6,76.7,135.6,162.2,32.6,20.0,6.4,3.3]},{name:'降水量',type:'bar',data:[2.6,5.9,9.0,26.4,28.7,70.7,175.6,182.2,48.7,18.8,6.0,2.3]},{name:'平均温度',type:'line',yAxisIndex:1,data:[2.0,2.2,3.3,4.5,6.3,10.2,20.3,23.4,23.0,16.5,12.0,6.2]}]},
"mix2":{color:['red', 'green','yellow'],title:{text:'某站点用户访问来源',subtext:'纯属虚构',x:'left'},tooltip:{trigger:'axis'},toolbox:{show:true,y:'bottom',feature:{mark:{show:false},dataView:{show:true,readOnly:false},magicType:{show:true,type:['line','bar','stack','tiled']},restore:{show:true},saveAsImage:{show:true}}},calculable:true,legend:{data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']},xAxis:[{type:'category',splitLine:{show:false},data:['周一','周二','周三','周四','周五','周六','周日']}],yAxis:[{type:'value',position:'right'}],series:[{name:'直接访问',type:'bar',data:[320,332,301,334,390,330,320]},{name:'邮件营销',type:'bar',tooltip:{trigger:'item'},stack:'广告',data:[120,132,101,134,90,230,210]},{name:'联盟广告',type:'bar',tooltip:{trigger:'item'},stack:'广告',data:[220,182,191,234,290,330,310]},{name:'视频广告',type:'bar',tooltip:{trigger:'item'},stack:'广告',data:[150,232,201,154,190,330,410]},{name:'搜索引擎',type:'line',data:[862,1018,964,1026,1679,1600,1570]},{name:'搜索引擎细分',type:'pie',tooltip:{trigger:'item',formatter:'{a}<br/>{b}:{c}({d}%)'},center:[160,130],radius:[0,50],itemStyle:{normal:{labelLine:{length:20}}},data:[{value:1048,name:'百度'},{value:251,name:'谷歌'},{value:147,name:'必应'},{value:102,name:'其他'}]}]},
"bar2":{color:['red', 'green','yellow'],title:{text: '某地区蒸发量和降水量',x:'center'},tooltip : {trigger: 'axis',axisPointer : {type : 'shadow'}},legend: {x:'left',data:['百度','谷歌','其他']},toolbox:{show:true,orient:'vertical',x:'right',y:'center',feature:{mark:{show:false},dataView:{show:false,readOnly:false},magicType:{show:false,type:['line','bar','stack','tiled']},restore:{show:true},saveAsImage:{show:true}}},calculable:true,xAxis:[{type:'category',data:['周一','周二','周三','周四','周五','周六','周日']}],yAxis:[{type:'value'}],series:[{name:'百度',type:'bar',barWidth:50,stack:'搜索引擎',data:[620,732,701,734,1090,1130,1120]},{name:'谷歌',type:'bar',stack:'搜索引擎',data:[120,132,101,134,290,230,220]},{name:'其他',type:'bar',stack:'搜索引擎',data:[62,82,91,84,109,110,120]}]}
//,
//"dataZoom1":{tooltip:{trigger:'axis'},legend:{data:['最高','最低']},toolbox:{show:true,feature:{mark:{show:false},dataZoom:{show:true},dataView:{show:true},magicType:{show:true,type:['line','bar','stack','tiled']},restore:{show:true},saveAsImage:{show:true}}},calculable:true,dataZoom:{show:true,realtime:true,start:20,end:80},xAxis:[{type:'category',boundaryGap:false,data:function(){var list=[];for(var i=1;i<=30;i++){list.push('2013-03-'+i);}return list;}()}],yAxis:[{type:'value'}],series:[{name:'最高',type:'line',data:function(){var list=[];for(var i=1;i<=30;i++){list.push(Math.round(Math.random()*30));}return list;}()},{name:'最低',type:'line',data:function(){var list=[];for(var i=1;i<=30;i++){list.push(Math.round(Math.random()*10));}return list;}()}]},
//"dynamicLineBar":{title:{text:'动态数据',subtext:'纯属虚构'},tooltip:{trigger:'axis'},legend:{data:['最新成交价','预购队列']},toolbox:{show:true,feature:{mark:{show:false},dataView:{show:true,readOnly:false},magicType:{show:true,type:['line','bar']},restore:{show:true},saveAsImage:{show:true}}},dataZoom:{show:false,start:0,end:100},xAxis:[{type:'category',boundaryGap:true,data:(function(){var now=newDate();var res=[];var len=10;while(len--){res.unshift(now.toLocaleTimeString().replace(/^\D*/,''));now=newDate(now-2000);}return res;})()},{type:'category',boundaryGap:true,data:(function(){var res=[];var len=10;while(len--){res.push(len+1);}return res;})()}],yAxis:[{type:'value',scale:true,name:'价格',boundaryGap:[0.2,0.2]},{type:'value',scale:true,name:'预购量',boundaryGap:[0.2,0.2]}],series:[{name:'预购队列',type:'bar',xAxisIndex:1,yAxisIndex:1,data:(function(){var res=[];var len=10;while(len--){res.push(Math.round(Math.random()*1000));}return res;})()},{name:'最新成交价',type:'line',data:(function(){var res=[];var len=10;while(len--){res.push((Math.random()*10+5).toFixed(1)-0);}return res;})()}]}
};